---
:consumer_key: hNBZZpcZh0GcJe49MU2xLlOyU
:consumer_secret: nVhtszISXQzToy3jjLJvtnvZA1vfEyNAHWCp1tgW2yk0dciPPq
:access_token: 795285745015648256-obrtQkYPcjP9CtYqwWVICgwbK2nmBTD
:access_token_secret: 6lUwMU7STWPVUtrJKcfUh3gvi0E2Ec73TIAQivfWlclhv
